import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Center from "../components/Center";
import Modal from "../components/Modal";
export default function Home({ data }) {
  console.log(data);
  return (
    <div className="h-screen overflow-hidden">
      <Head>
        <title>CollabTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex">
          <Sidebar />
          <Center data={data} />
          <Modal />
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const data = await fetch(
    "https://mock-youtube-api.herokuapp.com/api/videos"
  ).then((res) => res.json());

  return {
    props: {
      data,
    },
  };
}
